### PR TITLE
Added english language support for index.html

### PR DESCRIPTION
**Pull request by luk707**
I have added language support for the font page using jQuery. The script affects any html tag with a language attribute thus it can be easily extended to provide support for other languages.

### CODE REVIEW

**Comment by impasse** [comment]
3q very much,but I think do multi language support on server is better than do it in browser side,what do you think?

**Comment by luk707** [comment]
I agree, perhaps it could be done by passing the locale into swig. I'm new to swig so I'll have a read as to how it works and see what I can do.

**Comment by impasse** [comment]
I think it should be detect by http head 'Accept-Language', And https://www.npmjs.com/package/swig-i18n looks useful

**Comment by luk707** [comment]
Thanks, I'm gonna have a look at that in a bit

**Comment by luk707** [comment]
It should all work as expected now. I have added the localisation tags for error.swig, 404.swig and index.swig. All of the tags can be adjusted in configs so it should be easy to add new tokens and languages. I hope this is helpful ;)

**Pull request merged**
